talesofvalor/characters/urls.py
"""Router for views for characters."""
from django.urls import path

from .views import CharacterCreateView, CharacterUpdateView,\
    CharacterDetailView, CharacterDeleteView, CharacterResetView,\
    CharacterListView, CharacterPrintListView,\
    CharacterSetActiveView, CharacterSkillUpdateView,\
    CharacterConceptApproveView, CharacterHistoryApproveView,\
    ResetPointsView,\
    CharacterAddHeaderView, CharacterDropHeaderView, CharacterAddSkillView

app_name = 'characters'

urlpatterns = [
    path(
        'add/',
        CharacterCreateView.as_view(),
        name='character_create'
    ),
    path(
        '<int:pk>',
        CharacterDetailView.as_view(),
        name='character_detail'
    ),
    path(
        '<int:pk>/reset/',
        CharacterResetView.as_view(),
        name='character_reset'
    ),
    path(
        '<int:pk>/delete/',
        CharacterDeleteView.as_view(),
        name='character_delete'
    ),
    path(
        '<int:pk>/update/',
        CharacterUpdateView.as_view(),
        name='character_update'
    ),
    path(
        '<int:pk>/skill/',
        CharacterSkillUpdateView.as_view(),
        name='character_skill_update'
    ),
    path(
        '<int:pk>/setactive/',
        CharacterSetActiveView.as_view(),
        name='character_set_active'
    ),
    path(
        'approveconcept/',
        CharacterConceptApproveView.as_view(),
        name='concept_approve'
    ),
    path(
        'approvehistory/',
        CharacterHistoryApproveView.as_view(),
        name='history_approve'
    ),
    path(
        '',
        CharacterListView.as_view(),
        name='character_list'
    ),
    path(
        'print/<int:event_id>/',
        CharacterPrintListView.as_view(),
        name='character_print_list'
    ),
    path(
        'print/',
        CharacterPrintListView.as_view(),
        name='character_print_list'
    ),
    path(
        'reset_points/',
        ResetPointsView.as_view(),
        name='reset_points'
    ),
    # skill picking
    path(
        'addheader/',
        CharacterAddHeaderView.as_view(),
        name='header_add'
    ),
    path(
        'dropheader/',
        CharacterDropHeaderView.as_view(),
        name='header_drop'
    ),
    path(
        'addskill/',
        CharacterAddSkillView.as_view(),
        name='skill_add'
    ),
]

talesofvalor/players/urls.py
"""Router for views for players."""
from django.urls import path

from .views import PlayerUpdateView,\
    PlayerRedirectDetailView, PlayerDetailView, RegistrationView,\
    PlayerListView, PlayerDeleteView, PlayerViewSet, MassEmailView,\
    PlayerListRegistrationView, PlayerListAttendanceView,\
    MassGrantCPView,\
    PELListView, PELCreateView, PELDetailView, PELRedirectView, PELUpdateView

app_name = 'players'

urlpatterns = [
    path(
        'mail/',
        MassEmailView.as_view(),
        name='player_mail'
    ),
    path(
        'massgrantcps/',
        MassGrantCPView.as_view(),
        name='player_mass_grantcp'
    ),
    path(
        'select/',
        PlayerViewSet.as_view(),
        name='player_select'
    ),
    path(
        'register/mass/',
        PlayerListRegistrationView.as_view(),
        name='player_mass_registration'
    ),
    path(
        'attendance/mass/',
        PlayerListAttendanceView.as_view(),
        name='player_mass_attendance'
    ),
    path(
        'register/',
        RegistrationView.as_view(),
        name='registration'
    ),
    path(
        'home/',
        PlayerRedirectDetailView.as_view(),
        name='player_redirect_detail'
    ), 
    path(
        'pel/',
        PELListView.as_view(),
        name='pel_list'
    ),
    path(
        'pel/<int:pk>/',
        PELDetailView.as_view(),
        name='pel_detail'
    ),    
    path(
        'pel/<int:character_id>/<int:event_id>/',
        PELRedirectView.as_view(),
        name='pel_redirect'
    ),
    path(
        'pel/<int:pk>/edit',
        PELUpdateView.as_view(),
        name='pel_update'
    ),   
    path(
        'pel/add/<int:character_id>/<int:event_id>/',
        PELCreateView.as_view(),
        name='pel_create'
    ),
    path(
        '<int:pk>/',
        PlayerDetailView.as_view(),
        name='player_detail'
    ),
    path(
        '<int:pk>/update/',
        PlayerUpdateView.as_view(),
        name='player_update'
    ),
    path(
        '<int:pk>/delete/',
        PlayerDeleteView.as_view(),
        name='player_delete'
    ),
    path(
        '',
        PlayerListView.as_view(),
        name='player_list'
    ),
]

talesofvalor/skills/urls.py
"""Router for views for characters."""
from django.urls import path

from .views import HeaderCreateView, HeaderUpdateView,\
    HeaderDetailView, HeaderListView, HeaderDeleteView,\
    SkillCreateView, SkillUpdateView, SkillTreeView,\
    SkillDetailView, SkillListView, SkillDeleteView,\
    SkillSearchView, SkillNamesView

app_name = "skills"

urlpatterns = [
    path(
        'headers/',
        HeaderListView.as_view(),
        name='header_list'
    ),
    path(
        'headers/add/',
        HeaderCreateView.as_view(),
        name='header_create'
    ),
    path(
        'headers/<int:pk>/',
        HeaderDetailView.as_view(),
        name='header_detail'
    ),
    path(
        'headers/<int:pk>/edit/',
        HeaderUpdateView.as_view(),
        name='header_update'
    ),
    path(
        'headers/<int:pk>/delete/',
        HeaderDeleteView.as_view(),
        name='header_delete'
    ),
    path(
        '',
        SkillListView.as_view(),
        name='skill_list'
    ),
    path(
        'tree/',
        SkillTreeView.as_view(),
        name='skill_tree'
    ),
    path(
        'add/',
        SkillCreateView.as_view(),
        name='skill_create'
    ),
    path(
        '<int:pk>/',
        SkillDetailView.as_view(),
        name='skill_detail'
    ),
    path(
        '<int:pk>/edit/',
        SkillUpdateView.as_view(),
        name='skill_update'
    ),
    path(
        '<int:pk>/delete/',
        SkillDeleteView.as_view(),
        name='skill_delete'
    ),
    path(
        'api/names/',
        SkillNamesView.as_view(),
        name='skill_names'
    ),
    path(
        'api/',
        SkillSearchView.as_view(),
        name='skill_search'
    )
]

talesofvalor/urls.py
"""
Overarching routing for the application.

The routers for each of the sub-application (players, characters, etc) should
be included as a separate file.
"""

# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.conf import settings
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from cms.sitemaps import CMSSitemap

admin.autodiscover()

urlpatterns = [
    path('sitemap.xml', sitemap,
         {'sitemaps': {'cmspages': CMSSitemap}},
         name='django.contrib.sitemaps.views.sitemap'),
]


urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),  # NOQA
    path('hijack/', include('hijack.urls')),
    path('', include('django.contrib.auth.urls')),
    # main application
    path(  # router for utility services not specific to apps.
        'services/',
        include(
            'talesofvalor.services.urls'
        )
    ),
    path(  # router for the player application.
        'players/',
        include(
            'talesofvalor.players.urls'
        )
    ),
    path(  # router for the event application.
        'events/',
        include(
            'talesofvalor.events.urls'
        )
    ),
    path(  # router for the reports application.
        'reports/',
        include(
            'talesofvalor.reports.urls'
        )
    ),
    path(  # router for the event application.
        'registration/',
        include(
            'talesofvalor.registration.urls'
        )
    ),
    path(  # router for the between game skills application.
        'attendance/',
        include(
            'talesofvalor.attendance.urls'
        )
    ),
    path(  # router for the character application.
        'characters/',
        include(
            'talesofvalor.characters.urls'
        )
    ),
    path(  # router for the origins application.
        'origins/',
        include(
            'talesofvalor.origins.urls'
        )
    ),
    path(  # router for the skills application.
        'skills/',
        include(
            'talesofvalor.skills.urls'
        )
    ),
    path(  # router for the between game abilities application.
        'betweengameabilities/',
        include(
            'talesofvalor.betweengameabilities.urls'
        )
    ),
    path(  # router for the rules application.
        'rules/',
        include(
            'talesofvalor.rules.urls'
        )
    ),
    path(  # router for the comments application.
        'comments/',
        include(
            'talesofvalor.comments.urls'
        )
    ), 
    path('notifications/', include('django_nyt.urls')),
    path('wiki/', include('wiki.urls')),
    # for the main cms
    path('', include('cms.urls'))

)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
        + staticfiles_urlpatterns()

talesofvalor/characters/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import widgets

from talesofvalor.origins.models import Origin
from .models import Character


PLAYER_ALLOWED_FIELDS = [
    'name',
    'pronouns',
    'description',
    'history',
    'picture',
    'player_notes',
    'tradition'
]
NEW_PLAYER_FIELDS = [
    'people'
]


class CharacterForm(forms.ModelForm):
    tradition = forms.ModelChoiceField(
        queryset=Origin.objects.filter(type=Origin.TRADITION),
    )
    people = forms.ModelChoiceField(
        queryset=Origin.objects.filter(type=Origin.PEOPLE),
    )

    def __init__(self, *args, **kwargs):
        """
        use this to set up the different origins
        """
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if self.instance.id:
            for origin in Origin.ORIGIN_TYPES:
                # in case they had an origin that doesn't exist any more.
                try:
                    self.fields[origin[0]].initial = self.instance.origins.filter(type=origin[0]).first()
                except Origin.DoesNotExist:
                    pass
        # adjust fields for different users
        if user.has_perm('players.view_any_player'):
            allowed_fields = self.fields.keys()
        else:
            allowed_fields = PLAYER_ALLOWED_FIELDS
            if not self.instance.id:
                allowed_fields = allowed_fields + NEW_PLAYER_FIELDS
        self.fields = dict([(key, val) for key, val in self.fields.items() if key in allowed_fields])

    def save(self, commit=True):
        character = super().save(commit=commit)
        # if we have both the types of origins, then update the origins here.
        for origin in Origin.ORIGIN_TYPES:
            if origin[0] in self.cleaned_data:
                character.origins.remove(*character.origins.filter(type=origin[0]))
                character.origins.add(self.cleaned_data[origin[0]])
        return character

    class Meta:
        model = Character
        exclude = [
            'headers',
            'skills',
            'origins'
         ]


class CharacterSkillForm(forms.Form):
    """
    Allow skills to be added by a player to a character.

    The context of the tmeplate should have the list of the headers
    and associated skills so we can build a good looking form.
    """
    headers = forms.TypedMultipleChoiceField(
        required=False,
        widget=widgets.CheckboxSelectMultiple(),
        coerce=int
    )
    skills = forms.TypedMultipleChoiceField(
        required=False,
        widget=widgets.CheckboxSelectMultiple(),
        coerce=int
    )

    def __init__(self, *args, **kwargs):
        """
        Initializing the form.

        We have to break down the skills list that was sent so that we can
        indicate what the valid choices are.
        """
        # do pop first, so the parent doesn't get unexpected arguments.
        skills = kwargs.pop('skills')
        super(CharacterSkillForm, self).__init__(*args, **kwargs)
        self.fields['skills'].choices = \
            [(s.id, s.skill.name)
                for header in skills
                for s in header.headerskill_set.all()]
        self.fields['headers'].choices = \
            [(h.id, h.name) for h in skills]

    def clean(self):
        """
        Check and make sure the skills that have been chosen are valid.

        This should make sure that the character has enough points for the
        purchases AND that different skills don't interact badly.

        It has to take into account Grants, dabbling and different costs
        for things like jack of all trades etc.

        We should probably make a hash/dict based on headers that stores
        the expected costs per skill.  This was how it was done previously.
        """
        return super(CharacterSkillForm, self).clean()


class CharacterConceptApproveForm(forms.Form):
    """
    Form indicating approval of a characters history
    """
    character_id = forms.IntegerField()

    def clean(self):
        """
        Make sure the hisotry hasn't already been approved.
        """
        character_id = self.cleaned_data['character_id']
        character = Character.objects.get(pk=character_id)
        if character.concept_approved_flag:
            raise ValidationError(f"The concept for {character} has already been approved.")
        return super().clean()


class CharacterHistoryApproveForm(forms.Form):
    """
    Form indicating approval of a characters history
    """
    character_id = forms.IntegerField()

    def clean(self):
        """
        Make sure the hisotry hasn't already been approved.
        """
        character_id = self.cleaned_data['character_id']
        character = Character.objects.get(pk=character_id)
        if character.history_approved_flag:
            raise ValidationError(f"The history for {character} has already been approved.")
        return super().clean()


class ResetPointsForm(forms.Form):
    """
    Form for the approval of a reset points cap request to give some friction 
    to that request.

    Nothing really to do here at this time.
    """
    return_url = forms.CharField(widget=widgets.HiddenInput())

talesofvalor/characters/templates/characters/character_confirm_delete.html
{% extends "base.html" %}
{% load cms_tags %}


{% block bar_title %}{{ object.name }} : Characters{% endblock bar_title %}
{% block title %}{{ object.name }}{% endblock title %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.name }}"?</p>
    <input class="btn btn-danger" type="submit" value="Confirm" />
</form>
{% endblock content %}

talesofvalor/characters/templates/characters/character_detail.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{{ object.name }}{% if object.active_flag %} {% if object.pronouns %}&nbsp;({{ object.pronouns }}){% endif %} (active){% endif %}{% endblock title %}

{% block content %}
<div class="container character">
    Player: <a href="{% url 'players:player_detail' pk=object.player.pk %}">{{ object.player }}</a>
    <div class="no-print">
        <h2>{{ object.name }}{% if object.pronouns %}&nbsp;({{ object.pronouns }}){% endif %}</h2>
        {% if object.active_flag %}<span class="no-print">(active)</span>{% endif %}
    </div> 
    {% include "characters/includes/character_detail_inner.html" with object=object %}
    {% if perms.players.change_any_player %}
        <div class="character-body">
            <h2>Private Staff Notes:</h2>
            {{ object.staff_notes_hidden }} 
        </div>
        <div class="character-body">
            <h2>Character Log:</h2>
            <ul>
            {% for log in character_log %}
                <li>{{ log }}</li>
            {% endfor %}
            </ul>
        </div>
    </div>
        </div>
    {% endif %}

</div>
    
{% endblock content %}

talesofvalor/characters/templates/characters/character_influence_list.html
{% extends "base.html" %}
{% load cms_tags %}


{% block bar_title %}Character Influence{% endblock bar_title %}
{% block title %}Character Influence{% endblock title %}

{% block content %}


<div class="row">
    <div id="influence_list_filter" class="col-sm-12">
        <div>
            <form method="GET">
            <p>Search: <input name="name" type="text" value="{{ request.GET.name }}" />
            <button id="influence_list_filter_submit" class="btn btn-primary btn-submit" type="submit" name="search">Search</button>
            </p>
            </form>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <table id="influence_form" class="list list-influence table table-striped">
            <tr>
                <th>Select</th>
                <th>Name</th>
                <th>Current</th>
                <th>New</th>
            </tr>
            <tbody>
            {% for character in object_list %}
                <tr>
                    <td><input type="checkbox" class="save-select" name="character_select" data-id="{{ character.id }}" value="{{ character.id }}"{% if character.id in request.session.character_select %} checked{% endif %}></td>
                    <td>{{ character.name }}</td>
                    <td id="current_influence_{{ character.id }}" class="influence-current">{{ character.influence }}</td>
                    <td><form class="influence-update"><input type="text" name="infuence_{{ character.id }}" id="infuence_{{ character.id }}" value="{{ character.influence }}" class="influence-value"></form></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock content %}
{% block js %}
    {{ block.super }}
    <script type="text/javascript">
        var submitInfluence = ($eventTarget) => {
            var character_id = $eventTarget.prop('id').split("_")[1];
            var $influence_value = $("td#current_influence_" + character_id);
            $influence_value.removeClass('value_update');
            $.post('{% url "characters:influence_update" %}', {
                character_id: character_id,
                influence: $eventTarget.val(),
            }).done((data) => {
                    $influence_value.html(data.influence);
                    $influence_value.addClass('value_update');
            }).fail((data) => { 
                showError("Error", data.responseJSON.message);
                console.log(data);
            });


        } 

        $('.influence-update').on('submit', (event) => {
                event.preventDefault();
                submitInfluence($(event.currentTarget).children('.influence-value'));
            }
        );
        $('.influence-value').on('keydown', (event) => {
                // submit if are tabbing between.
                if (event.keyCode == 9) {
                    submitInfluence($(event.currentTarget));
                }
                
            }
        );
        // set up the selection handler
        $(document).ready(function(){
            $('.save-select').selectionSave({
                selectionEndPoint: "{% url 'characters:character_select' %}",
                valueSelector: "id"
            });
        });
    </script>
{% endblock %}

talesofvalor/characters/templates/characters/character_print_list.html
{% extends "base.html" %}
{% load cms_tags %}


{% block bar_title %}Print List{% endblock bar_title %}
{% block title %}{% endblock title %}

{% block content %}


{% for character in object_list %}
<div class="container character print-page-break">
    Player: <a href="{% url 'players:player_detail' pk=character.player.pk %}">{{ character.player }}</a>
    <div>
        <h2>{{ character.name }}{% if character.pronouns %}&nbsp;({{ character.pronouns }}){% endif %}</h2>
        {% if character.active_flag %}<span class="no-print">(active)</span>{% endif %}
    </div> 
    {% include "characters/includes/character_detail_inner.html" with object=character %}
    
</div>
{% if character.bgas %}
    <div class="print-page-break print-ability-list container">
        <h2>Between Game Abilities</h2>
        {% for ability in character.bgas %}
            <div class="bga-list-item">
                <div class="bga-question">
                    <h3>{{ ability.ability.header }}:{{ ability.ability.skill }}&nbsp;({{ ability.count }}):</h3>
                    <h3>Question:</h3>
                    {{ ability.question }}
                </div>
                <div class="bga-answer">
                    <h3>Answer:</h3>
                    {{ ability.answer }}
                </div>
            </div>
        {% endfor %}
    </div>
    {% endif %}
{% empty %}
<h1>No Characters registered or there is no next event created.</h1>
{% endfor %}


{% endblock content %}
{% block js %}
    {{ block.super }}
    <script type="text/javascript">
        window.addEventListener("load", print());
    </script>
{% endblock js %}

talesofvalor/characters/templates/characters/character_skill_form.html
{% extends "base.html" %}
{% load cms_tags utils %}

{% block title %}{{ object.name }}{% endblock title %}

{% block content %}
Player: <a href="{% url 'players:player_detail' pk=object.player.pk %}">{{ object.player }}</a>
<h1>Pick skills for {{ object.name }}{% if object.active_flag %} (active){% endif %}</h1>
<form id="charcterskill_form" action="" method="post">{% csrf_token %}
    {% include "characters/includes/character_stats.html" with object=object %}
    <hr />
    <h2>Available Character Points: <span id="character_point_display">{{ object.cp_available }}</span></h2>
    
    <hr />
    <div class="flex-container">
    {% for header in skills %}

    {% ifchanged header.category %}<h2 class="header-category"> {{ header.category }}</h2>{% endifchanged %}
    {% with skill_hash|dict_key:header.id as header_costs %}
    <div class="header-group group">
      <h3 class="header-label">
        <a href="{% url "skills:header_detail" pk=header.id %}">{{header.name }}</a>
        {% if not header_costs.purchased and not header.open_flag %}&nbsp;
          {% if 'cost' in header_costs %}({{header_costs.cost }} CPs){% endif %}&nbsp;
          <a href="{% url "characters:header_add" %}" class="add-header btn btn-primary" data-header-id="{{ header.id }}">add&nbsp;header</a>
          <a href="{% url "characters:header_drop" %}" class="drop-header btn btn-primary hidden" data-header-id="{{ header.id }}">drop&nbsp;header</a>
        {% else %}
          <a href="{% url "characters:header_add" %}" class="add-header btn btn-primary hidden" data-header-id="{{ header.id }}">add&nbsp;header</a>
          <a href="{% url "characters:header_drop" %}" class="drop-header btn btn-primary" data-header-id="{{ header.id }}">drop&nbsp;header</a>
        {% endif %}
      </h3>
        {% if header_costs.purchased or header.open_flag %}
            {% include "characters/includes/character_skill_update_item.html" with header_skills=header.skills.all %}
        {% endif %}
    </div>
    {% endwith %}
    {% endfor %}
    </div>
    {% if granted_skills %}
    <h1>Grants</h1>
    {% for skill in granted_skills %}
        <h2 class="header-label"><a href="{% url "skills:header_detail" pk=skill.header.id %}">{{ skill.header }}</a>:</h2> 
        {% include "characters/includes/character_skill_item.html" with skill=skill %}</br>
    {% endfor %}
    {% endif %}
        <tr>
            <td colspan="2" class="text-right">
                <input type="submit" value="Update" />
            </td>
        </tr>
    </table>
</form>
{% endblock content %}
{% block js %}
    {{ block.super }}
    <script type="text/javascript">
        let staff = {% if perms.players.view_any_player %}true{% else %}false{% endif %}
        var updateSkill = (eventTarget, character_id) => {
            // get the information
            const submit_url = $(eventTarget).attr('href')
            const skill_id = $(eventTarget).data('skill-id')
            const header_id = $(eventTarget).data('header-id')
            const vector = $(eventTarget).data('skill-vector')
            const original_purchased = $(eventTarget).data('original-purchased')
            // get the current cp:
            const $cp_available_display = $('#character_point_display');
            const cp_available = parseInt($cp_available_display.html());
            const $purchased_display = $(eventTarget).siblings('#' + header_id + "_" + skill_id + "_display");
            const purchased = parseInt($purchased_display.html());
            if ((purchased + vector >= original_purchased) || staff) {
                // update the skill points for a character
                $.post(submit_url, { 
                    skill_id: skill_id,
                    header_id: header_id,
                    character_id: character_id,
                    vector: vector,
                    cp_available: cp_available,
                 })
                .done((data) => {
                    console.log(data);
                    // We care getting the change in points back, so update the available points
                    $cp_available_display.html(cp_available + data.success);
                    $purchased_display.html(purchased + vector);
                    // see if we need to turn on or off the reduce button
                    const $reduce = $purchased_display.siblings('.update-skill[data-skill-vector="-1"]');
                    if ((purchased + vector <= original_purchased) && (!staff || (purchased + vector <= 0))) {
                        $reduce.addClass('invisible');
                    } else {
                        $reduce.removeClass('invisible');
                    }
                })
                .fail((data) => {
                    showError("Error Adding Skill", data.responseJSON.error);
                    console.log(data);
                });
            }

        };
        var updateInputSkill = (submit_url, skill_id, header_id, character_id, original_purchased) => {
            // get the current cp:
            const $cp_available_display = $('#character_point_display');
            const cp_available = parseInt($cp_available_display.html());
            const $checkbox = $('#id_header_' + header_id + "_skill_" + skill_id);
            // this is stuck this way because of this https://bugs.jquery.com/ticket/3827
            const checkbox_checked = $checkbox.is(':checked') ? false : true
            const purchased = checkbox_checked ? 1 : 0;
            const vector = checkbox_checked ? -1 : 1;
            if ((purchased + vector >= original_purchased) || staff)  {
                // update the skill points for a character
                $.post(submit_url, { 
                    skill_id: skill_id,
                    header_id: header_id,
                    character_id: character_id,
                    vector: vector,
                    cp_available: cp_available,
                 })
                .done((data) => {
                    // We care getting the change in points back, so update the available points
                    $cp_available_display.html(cp_available + data.success);
                    $checkbox.prop('checked', (vector < 0 ? false : true));
                })
                .fail((data) => {
                    showError("Error Adding Skill", data.responseJSON.error);
                    console.log(data);
                });
            }

        };
        $('.add-header').click((event) => {
            event.preventDefault();
            let header_id = $(event.currentTarget).data('header-id');
            let character_id = {{ object.id }};
            let submit_url = $(event.currentTarget).attr('href');
            let $header_group = $(event.currentTarget).parent().parent();
            // get the current cp:
            let cp_available = parseInt($('#character_point_display').html());
            // turn on the overlay
            $('#wait').show()
            $.post(submit_url, {
                header_id: header_id,
                character_id: character_id,
                cp_available: cp_available,
            })
            .done((data) => {
                // We care getting the change in points back, so update the available points
                cp_available = parseInt($('#character_point_display').html());
                $('#character_point_display').html(cp_available + data.success);
                $header_group.append(data.skills);
                $(event.currentTarget).hide();
                $(event.currentTarget).parent().find('.drop-header').show().removeClass('hidden');
            })
            .fail((data) => {
                showError("Error Adding Skill", data.responseJSON.error);
                console.log(data);
            })
            .always(function() {
                $('#wait').hide();
            });
            return false;
        });

        $('.drop-header').click((event) => {
            event.preventDefault();
            let header_id = $(event.currentTarget).data('header-id');
            let character_id = {{ object.id }};
            let submit_url = $(event.currentTarget).attr('href');
            let $header_group = $(event.currentTarget).parent().parent();
            // get the current cp:
            let cp_available = parseInt($('#character_point_display').html());
            $.post(submit_url, {
                header_id: header_id,
                character_id: character_id,
                cp_available: cp_available,
            })
            .done((data) => {
                // We care getting the change in points back, so update the available points
                cp_available = parseInt($('#character_point_display').html());
                $('#character_point_display').html(cp_available + data.success);

                $header_group.children().eq(1).remove();

                $(event.currentTarget).hide();
                $(event.currentTarget).parent().find('.add-header').show().removeClass('hidden');
            })
            .fail((data) => {
                showError("Error Dropping Skill", data.responseJSON.error);
                console.log(data);
            });
            return false;
        });

        $('.header-group').on('click', '.update-skill', (event) => {
            event.preventDefault();
            if ($(event.currentTarget).prop('nodeName') == 'A') {
                updateSkill(
                    event.currentTarget,
                    {{ object.id }}
                );
            } else {
                updateInputSkill(
                    $(event.currentTarget).attr('href'),
                    $(event.currentTarget).data('skill-id'),
                    $(event.currentTarget).data('header-id'),
                    {{ object.id }},
                    $(event.currentTarget).data('original-purchased'),
                );
            }
        });
    </script>
{% endblock %}