talesofvalor/origins/urls.py
"""Router for views for characters."""
from django.urls import path

from .views import OriginCreateView, OriginUpdateView,\
    OriginDetailView, OriginListView, OriginDeleteView


app_name = 'origins'

urlpatterns = [
    path(
        '',
        OriginListView.as_view(),
        name='origin_list'
    ),
    path(
        'add/',
        OriginCreateView.as_view(),
        name='origin_create'
    ),
    path(
        '<int:pk>/',
        OriginDetailView.as_view(),
        name='origin_detail'
    ),
    path(
        '<int:pk>/edit/',
        OriginUpdateView.as_view(),
        name='origin_update'
    ),
    path(
        '<int:pk>/delete/',
        OriginDeleteView.as_view(),
        name='origin_delete'
    )
]

talesofvalor/skills/urls.py
"""Router for views for characters."""
from django.urls import path

from .views import HeaderCreateView, HeaderUpdateView,\
    HeaderDetailView, HeaderListView, HeaderDeleteView,\
    SkillCreateView, SkillUpdateView, SkillTreeView,\
    SkillDetailView, SkillListView, SkillDeleteView,\
    SkillSearchView, SkillNamesView

app_name = "skills"

urlpatterns = [
    path(
        'headers/',
        HeaderListView.as_view(),
        name='header_list'
    ),
    path(
        'headers/add/',
        HeaderCreateView.as_view(),
        name='header_create'
    ),
    path(
        'headers/<int:pk>/',
        HeaderDetailView.as_view(),
        name='header_detail'
    ),
    path(
        'headers/<int:pk>/edit/',
        HeaderUpdateView.as_view(),
        name='header_update'
    ),
    path(
        'headers/<int:pk>/delete/',
        HeaderDeleteView.as_view(),
        name='header_delete'
    ),
    path(
        '',
        SkillListView.as_view(),
        name='skill_list'
    ),
    path(
        'tree/',
        SkillTreeView.as_view(),
        name='skill_tree'
    ),
    path(
        'add/',
        SkillCreateView.as_view(),
        name='skill_create'
    ),
    path(
        '<int:pk>/',
        SkillDetailView.as_view(),
        name='skill_detail'
    ),
    path(
        '<int:pk>/edit/',
        SkillUpdateView.as_view(),
        name='skill_update'
    ),
    path(
        '<int:pk>/delete/',
        SkillDeleteView.as_view(),
        name='skill_delete'
    ),
    path(
        'api/names/',
        SkillNamesView.as_view(),
        name='skill_names'
    ),
    path(
        'api/',
        SkillSearchView.as_view(),
        name='skill_search'
    )
]

talesofvalor/urls.py
"""
Overarching routing for the application.

The routers for each of the sub-application (players, characters, etc) should
be included as a separate file.
"""

# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.conf import settings
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from cms.sitemaps import CMSSitemap

admin.autodiscover()

urlpatterns = [
    path('sitemap.xml', sitemap,
         {'sitemaps': {'cmspages': CMSSitemap}},
         name='django.contrib.sitemaps.views.sitemap'),
]


urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),  # NOQA
    path('hijack/', include('hijack.urls')),
    path('', include('django.contrib.auth.urls')),
    # main application
    path(  # router for utility services not specific to apps.
        'services/',
        include(
            'talesofvalor.services.urls'
        )
    ),
    path(  # router for the player application.
        'players/',
        include(
            'talesofvalor.players.urls'
        )
    ),
    path(  # router for the event application.
        'events/',
        include(
            'talesofvalor.events.urls'
        )
    ),
    path(  # router for the reports application.
        'reports/',
        include(
            'talesofvalor.reports.urls'
        )
    ),
    path(  # router for the event application.
        'registration/',
        include(
            'talesofvalor.registration.urls'
        )
    ),
    path(  # router for the between game skills application.
        'attendance/',
        include(
            'talesofvalor.attendance.urls'
        )
    ),
    path(  # router for the character application.
        'characters/',
        include(
            'talesofvalor.characters.urls'
        )
    ),
    path(  # router for the origins application.
        'origins/',
        include(
            'talesofvalor.origins.urls'
        )
    ),
    path(  # router for the skills application.
        'skills/',
        include(
            'talesofvalor.skills.urls'
        )
    ),
    path(  # router for the between game abilities application.
        'betweengameabilities/',
        include(
            'talesofvalor.betweengameabilities.urls'
        )
    ),
    path(  # router for the rules application.
        'rules/',
        include(
            'talesofvalor.rules.urls'
        )
    ),
    path(  # router for the comments application.
        'comments/',
        include(
            'talesofvalor.comments.urls'
        )
    ), 
    path('notifications/', include('django_nyt.urls')),
    path('wiki/', include('wiki.urls')),
    # for the main cms
    path('', include('cms.urls'))

)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
        + staticfiles_urlpatterns()

talesofvalor/origins/models.py
"""
Origins (Attributes) of characters.

Describes character traits that are not learned or used in game.

These would be things like "peple", "nationality", "caste".

This should not be something that can be changed or learned.

These attributes may have an affect on the cost of abilities or grant
abilities or headers.
"""

from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.utils.translation import gettext_lazy as _

from djangocms_text_ckeditor.fields import HTMLField


class Origin(models.Model):
    """
    Backgrounds and Races and such.

    This will describe the attributes of a character.
    """

    PEOPLE = 'people'
    TRADITION = 'tradition'
    ORIGIN_TYPES = (
        (PEOPLE, 'People'),
        (TRADITION, 'Tradition'),
    )
    name = models.CharField(_("Name"), blank=False, max_length=100)
    description = HTMLField(blank=False)
    type = models.CharField(
        _("Type"),
        default=PEOPLE,
        choices=ORIGIN_TYPES,
        max_length=15
    )
    hidden_flag = models.BooleanField(_("Hidden?"), default=False)
    rules = GenericRelation('rules.Rule', related_query_name='rules')

    created = models.DateTimeField(
        'date published',
        auto_now_add=True,
        editable=False
    )
    modified = models.DateTimeField(
        'last updated',
        auto_now=True,
        editable=False
    )
    created_by = models.ForeignKey(
        User,
        editable=False,
        related_name='%(app_label)s_%(class)s_author',
        null=True,
        on_delete=models.SET_NULL
    )
    modified_by = models.ForeignKey(
        User,
        editable=False,
        related_name='%(app_label)s_%(class)s_updater',
        null=True,
        on_delete=models.SET_NULL
    )

    def __str__(self):
        return self.name

talesofvalor/origins/forms.py
from django import forms
from django.contrib.contenttypes.forms import generic_inlineformset_factory

from talesofvalor.rules.models import Rule
from .models import Origin

INCLUDE_FOR_EDIT = ["name", "type", "description"]


class OriginForm(forms.ModelForm):
    """
    Handle adding Origins.

    """

    class Media:
        js = ('js/lib/jquery.formset.js', 'js/lib/jquery-ui.min.js', )

    class Meta:
        model = Origin
        fields = INCLUDE_FOR_EDIT


RuleFormSet = generic_inlineformset_factory(
    Rule,
    fields='__all__',
    extra=1,
    can_delete=True
)

talesofvalor/origins/views.py
"""
These are views that are used for viewing and editing origins.

Origins function as backgrounds for characters and are mechanically equivalent.
"""
from django.contrib.auth.mixins import LoginRequiredMixin,\
    PermissionRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView,\
    DeleteView
from django.views.generic import DetailView, ListView

from .models import Origin
from .forms import OriginForm, RuleFormSet


class OriginCreateView(PermissionRequiredMixin, CreateView):
    """
    Allows the Creation of an origin
    """
    model = Origin
    form_class = OriginForm
    permission_required = ('origins.add_origin', )
    success_url = reverse_lazy('origins:origin_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['rule_formset'] = RuleFormSet(self.request.POST)
        else:
            context['rule_formset'] = RuleFormSet()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        rule_formset = context['rule_formset']
        if rule_formset.is_valid():
            self.object = form.save()
            rule_formset.instance = self.object
            rule_formset.save()
        else:
            return self.render_to_response(self.get_context_data(form=form))
        return redirect(self.success_url)


class OriginUpdateView(PermissionRequiredMixin, UpdateView):
    """
    Edits an origin that has already been created
    """

    model = Origin
    form_class = OriginForm
    permission_required = ('origins.change_origin', )
    success_url = reverse_lazy('origins:origin_list')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['rule_formset'] = RuleFormSet(self.request.POST, instance=self.object)
            context['rule_formset'].full_clean()
        else:
            context['rule_formset'] = RuleFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        rule_formset = context['rule_formset']
        if rule_formset.is_valid():
            self.object = form.save()
            rule_formset.instance = self.object
            rule_formset.save()
        else:
            return self.render_to_response(self.get_context_data(form=form))
        return redirect(self.success_url)



class OriginDeleteView(PermissionRequiredMixin, DeleteView):
    """
    Removes an origin permanantly.

    Removing an origin may have strange effects on characters with that origin.
    """

    model = Origin
    permission_required = ('origins.delete_origin', )
    success_url = reverse_lazy('origins:origin_list')


class OriginDetailView(DetailView):
    """
    Show the details for an origin.

    From here you can edit the details of a character or choose skills.
    """

    model = Origin
    fields = '__all__'


class OriginListView(LoginRequiredMixin, ListView):
    """
    Show the list of origins.

    From here you will be able to click to add a new origin,
    view, or edit an existing origin.
    """

    model = Origin
    paginate_by = 25

talesofvalor/origins/templates/origins/origin_confirm_delete.html
{% extends "base.html" %}
{% load cms_tags %}


{% block bar_title %}{{ object.name }} : Origins{% endblock bar_title %}
{% block title %}{{ object.name }}{% endblock title %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.name }}"?</p>
    <input class="btn btn-danger" type="submit" value="Confirm" />
</form>
{% endblock content %}

talesofvalor/origins/templates/origins/origin_detail.html
{% extends "base.html" %}
{% load cms_tags %}

{% block bar_title %}{{ object }} : Origins{% endblock bar_title %}
{% block title %}{{ object }}{% endblock title %}

{% block content %}
   <h1>{{ object.name }}</h1>
{% if perms.origins.change %}
 <a class="btn btn-primary" href="{% url 'origins:origin_update' pk=object.id %}">edit</a>
{% endif %}
{% if not object.hidden %}
<p>Hidden</p>
{% endif %}
<p><strong>Type:</strong> {{ object.type }}
<h2>Description:</h2>
{{ object.description }}
<!--
-- Origins don't yet have skills, so commenting this out until it's needed later.
<h2>Skills</h2>
<ul>
    {% for rule in object.rules.all %}
    <li><a href="{% url 'skills:skill_detail' pk=rule.skill.id %}">{{ rule.skill }}</a>&mdash;{{ rule.count }}</li>
    {% endfor %}
</ul>
-->
{% endblock content %}

talesofvalor/origins/templates/origins/origin_form.html
{% extends "base.html" %}
{% load cms_tags sekizai_tags %}

{% block bar_title %}{% if object.id %}{{ object.name }} : {% endif %}Origins{% endblock bar_title %}
{% block title %}{% if object.id %}{{ object.name }} : {% endif %}{{ object.name }}{% endblock title %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <table class="data">
        {{ form.as_table }}
    </table>   
    <div id="rule_formset"> 
        <h2>Grants</h2>
        {% if rule_formset.non_form_errors %}
        <ul class="errors">{{ rule_formset.non_form_errors }}</ul>
        {% endif %}
        <div class="alternating-container">
        {% for form in rule_formset %}
            <div class="rule">
            {{ form.id }}
            ( {{ form.name }} )
            Makes skill {{ form.skill }} cost {{ form.new_cost }} or {{ form.free }} free. <br /> Limit to {{ form.picks_remaining }} purchases. <br />
            {% if rule_formset.can_delete %}{{ form.DELETE }} Remove{% endif %}
            </div>
        {% endfor %}
        </div>
        {{ rule_formset.management_form }}
    </div> 
    <div class="text-right">
        <input class="btn btn-primary" type="submit" value="Update" />
        {% if object.id %}
            <a href="{% url "origins:origin_delete" pk=object.id %}" class="btn btn-danger">Delete</a></td>
        {% endif %}
    </div>
</form>

{% addtoblock "js" %}
<script type="text/javascript">
    $(function() {
        // Set up the formset to add nicely.
        $('#rule_formset .rule').formset({
            prefix: '{{ rule_formset.prefix }}',
            formCssClass: 'dynamic-{{ rule_formset.prefix }}',
            addCssClass: "add-row btn btn-primary"
            {% if rule_formset.initial_form_count > 0 %}, hideLastAddForm: true {% endif %}
        });

    });
</script>
{% endaddtoblock %}

{% endblock content %}

talesofvalor/origins/templates/origins/origin_list.html
{% extends "base.html" %}
{% load cms_tags %}


{% block bar_title %}Origins{% endblock bar_title %}
{% block title %}Origins{% endblock title %}

{% block content %}


<table class="list">
{% if perms.origin.add_origins %}
<tr>
    <td class="table-navigation content-align-right" colspan="4">
        <a class="btn btn-primary" href="{% url 'origins:origin_create' %}">add origin</a>
    </td>
</tr>
{% endif %}
<tr>
    <th>Name</th>
    <th>Description</th>
    <th>Type</th>
    <th>&nbsp;</th>
</tr>
{% for origin in object_list %}
<tr>
    <td><p><a href="{% url 'origins:origin_detail' pk=origin.id %}">{{ origin.name }}</a></p></td>
    <td>{{ origin.description|truncatewords_html:10 }}</td>
    <td><p>{{ origin.type }}</p></td>
    <td>
        <nav class="item-navigation">
            {% if perms.origins.change_origin %}<a href="{% url 'origins:origin_update' pk=origin.id %}">Edit</a>&nbsp;|&nbsp;{% endif %}
            {% if perms.origins.delete_origin %}<a href="{% url 'origins:origin_delete' pk=origin.id %}">Destroy</a>{% endif %}
        </nav>
    </td> 
</tr>
{% endfor %}
</table>

{% include "includes/pagination.html" %}


{% endblock content %}