talesofvalor/skills/urls.py
"""Router for views for characters."""
from django.urls import path

from .views import HeaderCreateView, HeaderUpdateView,\
    HeaderDetailView, HeaderListView, HeaderDeleteView,\
    SkillCreateView, SkillUpdateView, SkillTreeView,\
    SkillDetailView, SkillListView, SkillDeleteView,\
    SkillSearchView, SkillNamesView

app_name = "skills"

urlpatterns = [
    path(
        'headers/',
        HeaderListView.as_view(),
        name='header_list'
    ),
    path(
        'headers/add/',
        HeaderCreateView.as_view(),
        name='header_create'
    ),
    path(
        'headers/<int:pk>/',
        HeaderDetailView.as_view(),
        name='header_detail'
    ),
    path(
        'headers/<int:pk>/edit/',
        HeaderUpdateView.as_view(),
        name='header_update'
    ),
    path(
        'headers/<int:pk>/delete/',
        HeaderDeleteView.as_view(),
        name='header_delete'
    ),
    path(
        '',
        SkillListView.as_view(),
        name='skill_list'
    ),
    path(
        'tree/',
        SkillTreeView.as_view(),
        name='skill_tree'
    ),
    path(
        'add/',
        SkillCreateView.as_view(),
        name='skill_create'
    ),
    path(
        '<int:pk>/',
        SkillDetailView.as_view(),
        name='skill_detail'
    ),
    path(
        '<int:pk>/edit/',
        SkillUpdateView.as_view(),
        name='skill_update'
    ),
    path(
        '<int:pk>/delete/',
        SkillDeleteView.as_view(),
        name='skill_delete'
    ),
    path(
        'api/names/',
        SkillNamesView.as_view(),
        name='skill_names'
    ),
    path(
        'api/',
        SkillSearchView.as_view(),
        name='skill_search'
    )
]

talesofvalor/urls.py
"""
Overarching routing for the application.

The routers for each of the sub-application (players, characters, etc) should
be included as a separate file.
"""

# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.conf import settings
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from cms.sitemaps import CMSSitemap

admin.autodiscover()

urlpatterns = [
    path('sitemap.xml', sitemap,
         {'sitemaps': {'cmspages': CMSSitemap}},
         name='django.contrib.sitemaps.views.sitemap'),
]


urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),  # NOQA
    path('hijack/', include('hijack.urls')),
    path('', include('django.contrib.auth.urls')),
    # main application
    path(  # router for utility services not specific to apps.
        'services/',
        include(
            'talesofvalor.services.urls'
        )
    ),
    path(  # router for the player application.
        'players/',
        include(
            'talesofvalor.players.urls'
        )
    ),
    path(  # router for the event application.
        'events/',
        include(
            'talesofvalor.events.urls'
        )
    ),
    path(  # router for the reports application.
        'reports/',
        include(
            'talesofvalor.reports.urls'
        )
    ),
    path(  # router for the event application.
        'registration/',
        include(
            'talesofvalor.registration.urls'
        )
    ),
    path(  # router for the between game skills application.
        'attendance/',
        include(
            'talesofvalor.attendance.urls'
        )
    ),
    path(  # router for the character application.
        'characters/',
        include(
            'talesofvalor.characters.urls'
        )
    ),
    path(  # router for the origins application.
        'origins/',
        include(
            'talesofvalor.origins.urls'
        )
    ),
    path(  # router for the skills application.
        'skills/',
        include(
            'talesofvalor.skills.urls'
        )
    ),
    path(  # router for the between game abilities application.
        'betweengameabilities/',
        include(
            'talesofvalor.betweengameabilities.urls'
        )
    ),
    path(  # router for the rules application.
        'rules/',
        include(
            'talesofvalor.rules.urls'
        )
    ),
    path(  # router for the comments application.
        'comments/',
        include(
            'talesofvalor.comments.urls'
        )
    ), 
    path('notifications/', include('django_nyt.urls')),
    path('wiki/', include('wiki.urls')),
    # for the main cms
    path('', include('cms.urls'))

)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
        + staticfiles_urlpatterns()

talesofvalor/skills/models.py
"""
Skills and abilities that characters can use.

Characters have different things that they can do.

These skills have a cost to the character.

The costs can be changed or removed throught certain rules.

Skills may also come under "Headers" that must be purchased before
they can purchase the skills that belong to that header.
"""

from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.core.cache import cache
from django.db import models
from django.utils.translation import gettext_lazy as _

from djangocms_text_ckeditor.fields import HTMLField


class Skill(models.Model):
    """
    Skill representing things that characters can do.

    Attached to headers that are attached to characters.
    """
    name = models.CharField(max_length=100)
    # done like the to prevent circular imports
    prerequisites = GenericRelation('rules.Prerequisite')
    prerequisite_groups = GenericRelation('rules.PrerequisiteGroup')
    tag = models.CharField(max_length=100, blank=True, default='')
    description = HTMLField(blank=False)
    single_flag = models.BooleanField(
        _("Single Purchase?"),
        help_text=_("""
            Indicates that you only have to buy it once
            (like for weapon skills)
            """),
        default=False
    )
    bgs_flag = models.BooleanField(
        _("Between Game Ability"),
        help_text=_("""
            An ability that is typically used between events instead of during them.
            """),
        default=False
    )
    perk_flag = models.BooleanField(
        _("This is a Perk"),
        help_text=_("""
            A permanent ability that typically takes the form of a passive 
            benefit that permanently enhances a player’scapabilities.
            """),
        default=False
    )

    rules = GenericRelation('rules.Rule', related_query_name='rules')
    
    created = models.DateTimeField(
        'date published',
        auto_now_add=True,
        editable=False
    )
    modified = models.DateTimeField(
        'last updated',
        auto_now=True,
        editable=False
    )
    created_by = models.ForeignKey(
        User,
        editable=False,
        related_name='%(app_label)s_%(class)s_author',
        null=True,
        on_delete=models.SET_NULL
    )
    modified_by = models.ForeignKey(
        User,
        editable=False,
        related_name='%(app_label)s_%(class)s_updater',
        null=True,
        on_delete=models.SET_NULL
    )

    class Meta:
        ordering = ['headerskill__cost', 'name']
        """Add permissions."""

        permissions = (
            ("view_all_skills", "View All Skills when choosing"),
        )

    def __str__(self):
        return self.name

    @property
    def headers(self):
        return ', '.join([i for i in self.headerskill_set.values_list(
            "header__name",
            flat=True
        )])

    @classmethod
    def skillhash(cls):
        """
        Create the base hash of skills and costs.
        {
            51: {'skills': {
                    248: {'cost': 3, 'purchased': 0}, 
                    49: {'cost': 3, 'purchased': 0},
                    250: {'cost': 3, 'purchased': 0},
                    251: {'cost': 3, 'purchased': 0},
                    252: {'cost': 3, 'purchased': 0}
                },
                'cost': 0}}
        }
        It will be updated by the character.
        """
        if skill_hash := cache.get("skill_hash"):
            return skill_hash
        headers = Header.objects.all().order_by('-open_flag')
        skill_hash = {
            h.id: {
                'skills': {
                    s.skill_id: {
                        'name': s.skill.name,
                        'headerskill': s.id,
                        'cost': s.cost,
                        'purchased': 0
                    }
                    for s in h.headerskill_set.all()
                }
            }
            for h in headers
        }
        for h in headers:
            skill_hash[h.id]['cost'] = h.cost

        # cache until a skill or header is updated
        cache.set("skill_hash", skill_hash, None)
        return skill_hash


class Header(models.Model):
    """
    Header containing skills.

    Object that skills are attached to.  Every skill belongs to a header
    of some sort.

    Skills can be part of multiple headers with different costs
    under each.
    """

    name = models.CharField(max_length=100)
    category = models.CharField(max_length=100, blank=True, default='')
    description = HTMLField(blank=False)
    cost = models.PositiveIntegerField(null=False, blank=False)
    hidden_flag = models.BooleanField("hidden?", default=False)
    open_flag = models.BooleanField(
        "open?", 
        help_text=_("""
        Header is automatically 'open' without the need for purchase.
        """),
        default=False
    )
    skills = models.ManyToManyField(Skill, through='HeaderSkill')

    rules = GenericRelation('rules.Rule', related_query_name='rules')
    # done like this to prevent circular imports
    prerequisites = GenericRelation('rules.Prerequisite')
    prerequisite_groups = GenericRelation('rules.PrerequisiteGroup')
    created = models.DateTimeField('date published', auto_now_add=True, editable=False)
    modified = models.DateTimeField('last updated', auto_now=True, editable=False)
    created_by = models.ForeignKey(
        User,
        editable=False,
        related_name='%(app_label)s_%(class)s_author',
        null=True,
        on_delete=models.SET_NULL
    )
    modified_by = models.ForeignKey(
        User,
        editable=False,
        related_name='%(app_label)s_%(class)s_updater',
        null=True,
        on_delete=models.SET_NULL
    )

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class HeaderSkill(models.Model):
    """
    Links up the Header and skills.

    This also holds the cost for a skill under a specific header,
    because skills cost different amounts under different headers.
    """

    header = models.ForeignKey(Header, on_delete=models.CASCADE)
    skill = models.ForeignKey(Skill, on_delete=models.CASCADE)
    cost = models.PositiveIntegerField(null=False, blank=False)
    magic_flag = models.BooleanField(
        _("Is this magical?"),
        help_text=_("""
            Indicates that this skill is magical.
            """),
        default=False
    )
    capstone_flag = models.BooleanField(
        _("Is this a capstone?"),
        help_text=_("""
            Indicates that this is a capstone granted when
            requirements are met.
            (like for weapon skills)
            """),
        default=False
    )

    class Meta:
        ordering = ['cost', 'skill__name']

    def __str__(self):
        return "{header}:{skill}[{cost}]".format(
            header=self.header,
            skill=self.skill,
            cost=self.cost
        )

talesofvalor/skills/forms.py
from django import forms
from django.contrib.contenttypes.forms import generic_inlineformset_factory

from talesofvalor.rules.models import Rule

from .models import Skill, Header, HeaderSkill


INCLUDE_FOR_EDIT_HEADER = ["name", "category", "description", "cost", "hidden_flag", "open_flag"]
INCLUDE_FOR_EDIT_SKILL = ["name", "tag", "description", "single_flag", "bgs_flag", "perk_flag"]


class HeaderForm(forms.ModelForm):
    """
    Handle adding a header.

    The form will allow users to add the header and set up prerequisites.
    """

    class Media:
        js = ('js/lib/jquery.formset.js', 'js/lib/jquery-ui.min.js', )

    class Meta:
        model = Header
        fields = INCLUDE_FOR_EDIT_HEADER


class SkillForm(forms.ModelForm):
    """
    Handle adding skills.

    The form will allow users to add the skill to multiple headers at multiple
    different costs.
    """

    class Media:
        js = ('js/lib/jquery.formset.js', 'js/lib/jquery-ui.min.js', )

    class Meta:
        model = Skill
        fields = INCLUDE_FOR_EDIT_SKILL


HeaderSkillFormSet = forms.inlineformset_factory(
    Skill,
    HeaderSkill,
    fields=('header', 'cost', 'capstone_flag', 'magic_flag'),
    extra=1,
    can_delete=True
)

RuleFormSet = generic_inlineformset_factory(
    Rule,
    fields='__all__',
    extra=1,
    can_delete=True
)

talesofvalor/skills/templates/skills/header_confirm_delete.html
{% extends "base.html" %}
{% load cms_tags %}


{% block bar_title %}{{ object.name }} : Origins{% endblock bar_title %}
{% block title %}{{ object.name }}{% endblock title %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.name }}"?</p>
    <input class="btn btn-danger" type="submit" value="Confirm" />
</form>
{% endblock content %}

talesofvalor/skills/templates/skills/header_detail.html
{% extends "base.html" %}
{% load cms_tags %}


{% block bar_title %}{{ object.name }} : Headers{% endblock bar_title %}
{% block title %}{{ object.name }}{% endblock title %}

{% block content %}

<h1>{{ object.name }} {% if object.hidden_flag %}<span class="text-danger">(hidden)</span>{% endif %}</h1>
{% if perms.skills.change %}
 <a class="btn btn-primary" href="{% url 'skills:header_update' pk=object.id %}">edit</a>
{% endif %}
<p>Open for {{ object.cost }} CPs</p>
<h2>Description:</h2>
{{ object.description }}
<h2>Skills</h2>
<ul>
	{% for headerskill in object.headerskill_set.all %}
	<li><a href="{% url 'skills:skill_detail' pk=headerskill.skill.id %}">{{ headerskill.skill }}</a>&mdash;{{ headerskill.cost }} CPs</li>
	{% endfor %}
</ul>

{% endblock content %}

talesofvalor/skills/templates/skills/header_list.html
{% extends "base.html" %}
{% load cms_tags %}


{% block bar_title %}Headers{% endblock bar_title %}
{% block title %}Headers{% endblock title %}

{% block content %}

 <div class="row">
      <div class="col-sm-8">
          <div class="box">
            <h3>Filters</h3>
            <form method="GET" action="">
              <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-secondary{% if 'hidden_flag' not in request.GET or request.GET.hidden_flag == '' %} active{% endif %}">
                  <input type="radio" name="hidden_flag" id="hidden-flag_all" autocomplete="off" value="">All
                </label>
                <label class="btn btn-secondary{% if request.GET.hidden_flag == '0' %} active{% endif %}">
                  <input type="radio" name="hidden_flag" id="hidden-flag_false" autocomplete="off" value="0"{% if request.GET.hidden_flag == '0' %} checked{% endif %}>Visible
                </label>
                <label class="btn btn-secondary{% if request.GET.hidden_flag == '1' %} active{% endif %}"">
                  <input type="radio" name="hidden_flag" id="hidden-flag_true" autocomplete="off" value="1"{% if request.GET.hidden_flag == '1' %} checked{% endif %}> Hidden
                </label>
              </div>
              <table class="data">
                <tr>
                  <th><label for="name">Name:</label></th><td><input type="text" value="{{request.GET.name}}" name="name"/></td>
                </tr>
                <tr>
                  <th><label for="category">Category:</label></th><td><input type="text" value="{{request.GET.category}}" name="category"/></td>
                </tr>
                <tr>
                  <th><label for="description">Description:</label></th><td><input type="text" value="{{request.GET.description}}" name="description"/></td>
                </tr>
                <tr>
                  <th>&nbsp;</th><td class="text-right"><input class="btn btn-primary" type="submit" name="submit" value="submit" /></td>
                </tr>
              </table>
          </form>
 
          </div>
      </div>
      {% if perms.skills.add_header %}
      <div class="col-sm-4">
          <div class="box text-right">
            <a class="btn btn-primary" href="{% url 'skills:header_create' %}">add header</a>
          </div>
      </div>
      {% endif %}
  </div>

<div class="row col-sm-12">
<table class="list">
<tr>
    <th>Name</th>
    <th>Description</th>
    <th>&nbsp;</th>
</tr>
{% for header in object_list %}
<tr>
    <td><p><a href="{% url 'skills:header_detail' pk=header.id %}">{{ header.name }}</a></p></td>
    <td>{{ header.description|truncatewords_html:10 }}</td>
    <td>
        <nav class="item-navigation">
            {% if perms.skills.change_header %}<a href="{% url 'skills:header_update' pk=header.id %}">Edit</a>&nbsp;|&nbsp;{% endif %}
            {% if perms.skills.delete_header %}<a href="{% url 'skills:header_delete' pk=header.id %}">Destroy</a>{% endif %}
        </nav>
    </td> 
</tr>
{% endfor %}
</table>
</div>

{% if is_paginated %}

<div class="row col-sm-12 text-center">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">&laquo;</a></li>
    {% else %}
      <li class="page-item disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">&raquo;</a></li>
    {% else %}
      <li class="page-item disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
</div>
{% endif %}

{% endblock content %}

talesofvalor/skills/templates/skills/skill_confirm_delete.html
{% extends "base.html" %}
{% load cms_tags %}


{% block bar_title %}{{ object.name }} : Origins{% endblock bar_title %}
{% block title %}{{ object.name }}{% endblock title %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.name }}"?</p>
    <input class="btn btn-danger" type="submit" value="Confirm" />
</form>
{% endblock content %}

talesofvalor/skills/templates/skills/skill_detail.html
{% extends "base.html" %}
{% load cms_tags %}


{% block bar_title %}{{ object.name }} : Headers{% endblock bar_title %}
{% block title %}{{ object.name }}{% endblock title %}

{% block content %}

<h1>{{ object.name }}</h1>
{% if perms.skills.change_skill %}
 <a class="btn btn-primary" href="{% url 'skills:skill_update' pk=object.id %}">edit</a>
{% endif %}
<h2>Description:</h2>
{{ object.description }}
<h2>Headers</h2>
<ul>
	{% for headerskill in object.headerskill_set.all %}
	<li><a href="{% url 'skills:header_detail' pk=headerskill.header.id %}">{{ headerskill.header }}</a>&mdash;{{ headerskill.cost }} CPs</li>
	{% endfor %}
</ul>

{% endblock content %}

talesofvalor/skills/templates/skills/skill_list.html
{% extends "base.html" %}
{% load cms_tags %}


{% block bar_title %}Skills{% endblock bar_title %}
{% block title %}Skills{% endblock title %}

{% block content %}

<div class="row">
    <div class="col-sm-8">
        <div class="box">
          <h3>Filters</h3>
          <form method="GET" action="">
            <div class="btn-group btn-group-toggle" data-toggle="buttons">
              <label class="btn btn-secondary{% if request.GET.bgs_flag == '1' %} active{% endif %}"">
                <input type="checkbox" name="bgs_flag" id="bgs_flag" autocomplete="off" value="1"{% if request.GET.bgs_flag == '1' %} checked{% endif %}> BGA
              </label>
              <label class="btn btn-secondary{% if request.GET.hidden_flag == '1' %} active{% endif %}"">
                <input type="checkbox" name="hidden_flag" id="hidden_flag" autocomplete="off" value="1"{% if request.GET.hidden_flag == '1' %} checked{% endif %}> Hidden
              </label>
              <label class="btn btn-secondary{% if request.GET.unlinked_flag == '1' %} active{% endif %}"">
                <input type="checkbox" name="unlinked_flag" id="unlinked_flag" autocomplete="off" value="1"{% if request.GET.unlinked_flag == '1' %} checked{% endif %}> Unlinked
              </label>
            </div>
            <table class="data">
              <tr>
                <th><label for="name">Name:</label></th><td><input type="text" value="{{request.GET.name}}" name="name"/></td>
              </tr>
              <tr>
                <th><label for="description">Description:</label></th><td><input type="text" value="{{request.GET.description}}" name="description"/></td>
              </tr>
              <tr>
                <th>&nbsp;</th><td class="text-right"><input class="btn btn-primary" type="submit" name="submit" value="submit"/></td>
              </tr>
            </table>
        </form>

        </div>
    </div>
    {% if perms.skills.add_skill %}
    <div class="col-sm-4">
        <div class="box text-right">
        <a class="btn btn-primary" href="{% url 'skills:skill_create' %}">add skill</a>
        </div>
    </div>
    {% endif %}
</div>


<div class="row col-sm-12">
<table class="list">
<tr>
    <th>Name</th>
    <th>Description</th>
    <th>Header</th>
    <th>&nbsp;</th>
</tr>
{% for skill in object_list %}
<tr>
    <td><p><a href="{% url 'skills:skill_detail' pk=skill.id %}">{{ skill.name }}</a></p></td>
    <td>{{ skill.description|truncatewords_html:10 }}</td>
    <td><p>{% for h in skill.header_set.all %}<a href="{% url 'skills:header_detail' pk=h.id %}">{{ h }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</p></td>
    <td>
        <nav class="item-navigation">
            {% if perms.skills.change_skill %}<a href="{% url 'skills:skill_update' pk=skill.id %}">Edit</a>&nbsp;|&nbsp;{% endif %}
            {% if perms.skills.delete_skill %}<a href="{% url 'skills:skill_delete' pk=skill.id %}">Destroy</a>{% endif %}
        </nav>
    </td> 
</tr>
{% endfor %}
</table>
</div>

{% if is_paginated %}

<div class="row col-sm-12 text-center">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">&laquo;</a></li>
    {% else %}
      <li class="page-item disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">&raquo;</a></li>
    {% else %}
      <li class="page-item disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
</div>
{% endif %}

{% endblock content %}

talesofvalor/skills/templates/skills/skill_tree.html
{% extends "base.html" %}
{% load cms_tags %}


{% block bar_title %}Skill Tree{% endblock bar_title %}
{% block title %}Skill Tree{% endblock title %}

{% block content %}


<div class="row col-sm-12">
<table class="list">

{% for header in object_list %}

    {% ifchanged header.category %}<h2> {{ header.category }}</h2>{% endifchanged %}
    <h3><a href="{% url 'skills:header_detail' pk=header.id %}">{{ header.name }}</a></h3>
    {% for skill in header.skills.all %}
      <p><a href="{% url 'skills:skill_detail' pk=skill.id %}">{{ skill.name }}</a></p>
    {% endfor %}
{% endfor %}
</table>
</div>

{% endblock content %}