talesofvalor/betweengameabilities/urls.py
"""Router for views for characters."""
from django.urls import path

from .views import BetweenGameAbilityCreateView, BetweenGameAbilityUpdateView,\
    BetweenGameAbilityDetailView, BetweenGameAbilityListView,\
    BetweenGameAbilityDeleteView

app_name = 'betweengameabilities'

urlpatterns = [
    path(
        '',
        BetweenGameAbilityListView.as_view(),
        name='betweengameability_list'
    ),
    path(
        'add/',
        BetweenGameAbilityCreateView.as_view(),
        name='betweengameability_create'
    ),
    path(
        '<int:pk>/',
        BetweenGameAbilityDetailView.as_view(),
        name='betweengameability_detail'
    ),
    path(
        '<int:pk>/edit/',
        BetweenGameAbilityUpdateView.as_view(),
        name='betweengameability_update'
    ),
    path(
        '<int:pk>/delete/',
        BetweenGameAbilityDeleteView.as_view(),
        name='betweengameability_delete'
    )
]

talesofvalor/events/urls.py
"""Router for views for events."""
from django.urls import path

from .views import EventCreateView, EventUpdateView, EventListView,\
    EventPastListView, EventCharacterPrintListView,\
    EventDetailView, PlayerRegistrationRedirectView,\
    PlayerRegistrationNoEventView, PlayerRegistrationView,\
    CastRegistrationRedirectView, CastRegistrationView,\
    EventRegistrationItemDetailView, EventRegistrationItemListView,\
    EventRegistrationItemCreateView, EventRegistrationItemUpdateView

app_name = 'events'

urlpatterns = [
    path(
        'add/',
        EventCreateView.as_view(),
        name='event_create'
    ),
    path(
        '<int:pk>/update/',
        EventUpdateView.as_view(),
        name='event_update'
    ),
    path(
        '<int:pk>/',
        EventDetailView.as_view(),
        name='event_detail'
    ),
    path(
        '<int:pk>/print/',
        EventCharacterPrintListView.as_view(),
        name='event_character_print'
    ),
    path(
        'char/<int:character>/',
        EventListView.as_view(),
        name='event_list'
    ),    
    path(
        'register/',
        PlayerRegistrationRedirectView.as_view(),
        name='redirect_register'
    ),
    path(
        'event_no_next_event/',
        PlayerRegistrationNoEventView.as_view(),
        name='event_no_next_event'
    ),
    path(
        '<int:pk>/register/',
        PlayerRegistrationView.as_view(),
        name='register'
    ),
    path(
        'register-cast/',
        CastRegistrationRedirectView.as_view(),
        name='redirect_register_cast'
    ),
    path(
        '<int:pk>/register-cast/',
        CastRegistrationView.as_view(),
        name='register_cast'
    ),  
    path(
        'past/',
        EventPastListView.as_view(),
        name='event_past_list'
    ),
    path(
        '',
        EventListView.as_view(),
        name='event_list'
    ),
    path(
        'registrationitems/<int:pk>/',
        EventRegistrationItemDetailView.as_view(),
        name='eventregistrationitem_detail'
    ),
    path(
        'registrationitems/',
        EventRegistrationItemListView.as_view(),
        name='eventregistrationitem_list'
    ),
    path(
        'registrationitems/add/',
        EventRegistrationItemCreateView.as_view(),
        name='eventregistrationitem_create'
    ),
    path(
        'registrationitems/<int:pk>/update/',
        EventRegistrationItemUpdateView.as_view(),
        name='eventregistrationitem_update'
    ),
]

talesofvalor/registration/urls.py
"""Router for views for events."""
from django.urls import path, re_path

from .views import RegistrationSendView, RegistrationCompleteView,\
    RegistrationDetailView, RegistrationUpdateView,\
    RegistrationRequestListView, RegistrationRequestApproveFormView,\
    RegistrationRequestDenyFormView,\
    RegistrationRequestDetailView, RegistrationListView,\
    RegistrationRequestAlreadyPaidView, RegistrationRequestPayAtDoorView,\
    RegistrationRequestDeleteView

app_name = 'registration'

urlpatterns = [
    path(
        'send/',
        RegistrationSendView.as_view(),
        name='create'
    ),
    path(
        'complete/',
        RegistrationCompleteView.as_view(),
        name='complete'
    ),
    path(
        '<int:pk>/',
        RegistrationDetailView.as_view(),
        name='detail'
    ),
    path(
        '<int:pk>/edit/',
        RegistrationUpdateView.as_view(),
        name='edit'
    ),
    re_path(
        'event/(?P<event>[0-9]+)/((?P<player>[0-9]+)/)?',
        RegistrationListView.as_view(),
        name='list'
    ),
    path(
        'request/<int:pk>/alreadypaid/',
        RegistrationRequestAlreadyPaidView.as_view(),
        name='request_already_paid'
    ),
    path(
        'request/<int:pk>/approve/',
        RegistrationRequestApproveFormView.as_view(),
        name='request_approve'
    ),
    path(
        'request/<int:pk>/deny/',
        RegistrationRequestDenyFormView.as_view(),
        name='request_deny'
    ),
    path(
        'request/<int:pk>/payatdoor/',
        RegistrationRequestPayAtDoorView.as_view(),
        name='request_pay_at_door'
    ),
    path(
        'request/<int:pk>/delete/',
        RegistrationRequestDeleteView.as_view(),
        name='request_delete'
    ),   
    path(
        'request/<int:pk>/',
        RegistrationRequestDetailView.as_view(),
        name='request_detail'
    ),
    path(
        'request/',
        RegistrationRequestListView.as_view(),
        name='request_list'
    ),
]

talesofvalor/urls.py
"""
Overarching routing for the application.

The routers for each of the sub-application (players, characters, etc) should
be included as a separate file.
"""

# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.conf import settings
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from cms.sitemaps import CMSSitemap

admin.autodiscover()

urlpatterns = [
    path('sitemap.xml', sitemap,
         {'sitemaps': {'cmspages': CMSSitemap}},
         name='django.contrib.sitemaps.views.sitemap'),
]


urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),  # NOQA
    path('hijack/', include('hijack.urls')),
    path('', include('django.contrib.auth.urls')),
    # main application
    path(  # router for utility services not specific to apps.
        'services/',
        include(
            'talesofvalor.services.urls'
        )
    ),
    path(  # router for the player application.
        'players/',
        include(
            'talesofvalor.players.urls'
        )
    ),
    path(  # router for the event application.
        'events/',
        include(
            'talesofvalor.events.urls'
        )
    ),
    path(  # router for the reports application.
        'reports/',
        include(
            'talesofvalor.reports.urls'
        )
    ),
    path(  # router for the event application.
        'registration/',
        include(
            'talesofvalor.registration.urls'
        )
    ),
    path(  # router for the between game skills application.
        'attendance/',
        include(
            'talesofvalor.attendance.urls'
        )
    ),
    path(  # router for the character application.
        'characters/',
        include(
            'talesofvalor.characters.urls'
        )
    ),
    path(  # router for the origins application.
        'origins/',
        include(
            'talesofvalor.origins.urls'
        )
    ),
    path(  # router for the skills application.
        'skills/',
        include(
            'talesofvalor.skills.urls'
        )
    ),
    path(  # router for the between game abilities application.
        'betweengameabilities/',
        include(
            'talesofvalor.betweengameabilities.urls'
        )
    ),
    path(  # router for the rules application.
        'rules/',
        include(
            'talesofvalor.rules.urls'
        )
    ),
    path(  # router for the comments application.
        'comments/',
        include(
            'talesofvalor.comments.urls'
        )
    ), 
    path('notifications/', include('django_nyt.urls')),
    path('wiki/', include('wiki.urls')),
    # for the main cms
    path('', include('cms.urls'))

)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
        + staticfiles_urlpatterns()

talesofvalor/events/models.py
"""
Describes the game events.

These models describe the game events.
"""
from datetime import date, timedelta

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from djangocms_text_ckeditor.fields import HTMLField


EVENT_MEALPLAN_PRICE = 35


class Event(models.Model):
    name = models.CharField(
        help_text=_("For reference, such as \"Spring 2, 2010\""),
        max_length=255
    )
    event_date = models.DateField()
    pel_due_date = models.DateField()
    bgs_due_date = models.DateField()
    oog_p = models.BooleanField(_("Out of game event"), default=False)
    bgs_p = models.BooleanField(_("Allow Between Game Skills"), default=True)
    notes = HTMLField(blank=True, default='')
    summary = HTMLField(blank=True, default='')

    class Meta:
        ordering = ['-event_date']
        permissions = (
            ("cast_registration", "Can register as a cast member."),
        )


    def __str__(self):
        return "{} - {}".format(
            self.name,
            self.event_date.strftime("%m-%d-%Y")
        )

    @classmethod
    def previous_event(cls):
        event_range_beginning = date.today() - timedelta(days=3)
        try:
            return cls.objects.filter(event_date__lt=event_range_beginning)\
                .order_by('-event_date').first()
        except cls.DoesNotExist:
            return None

    @classmethod
    def next_event(cls):
        '''
        When looking for the next event, make sure we are not in a 
        current event.
        '''
        event_range_end = date.today() - timedelta(days=3)
        try:
            return cls.objects.filter(event_date__gt=event_range_end)\
                .order_by('event_date').first()
        except cls.DoesNotExist:
            return None

    @property
    def previous(self):
        try:
            return type(self).objects.filter(event_date__lt=self.event_date)\
                .order_by('-event_date').first()
        except self.DoesNotExist:
            return None

    @property
    def next(self):
        try:
            return type(self).objects.filter(event_date__gt=self.event_date)\
                .order_by('event_date').first()
        except self.DoesNotExist:
            return None

    @property
    def bga_past_due(self):
        """
        Has the past due date passed?
        """
        now = timezone.localtime(timezone.now())
        if now.date() > self.bgs_due_date:
            return True
        return False

    def attended(self, character):
        return self.attendance_set.filter(player=character.player).exists()

    def attended_player(self, player):
        return self.attendance_set.filter(player=player).exists()

    def get_absolute_url(self):
        """
        Return the absolute URL.

        This is the canonical URL to show the detail page
        for an Event.
        """
        return reverse('events:event_detail', kwargs={'pk': self.pk})


class EventRegistrationItem(models.Model):
    """
    A structure that binds up the different ways that an event could be
    registered for.

    For example, and Item might have a season's worth of events.  Or a Years.
    """
    name = models.CharField(
        help_text=_("For reference, such as \"Season Pass\""),
        max_length=255
    )
    order = models.IntegerField(
        help_text=_("What order should this appear on the page?"),
        default=0
    )
    events = models.ManyToManyField(Event, related_name="events")
    available = models.BooleanField(
        help_text=_("Is this still available?"),
        default=True
    )
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)

    def get_absolute_url(self):
        """
        Return the absolute URL.

        This is the canonical URL to show the detail page
        for an EventRegistrationItem.
        """
        return reverse('events:eventregistrationitem_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return "{}".format(
            self.name
        )

    class Meta:
        ordering = ['order']

talesofvalor/events/forms.py
from datetime import date

from django import forms

from .models import Event


class EventForm(forms.ModelForm):
    """
    Show the form for entering events.

    We need a form for entering events rather than just using that provided
    by the generic view (in events/views.py) because we have to add
    the datepicker.
    """
    def __init__(self, *args, **kwargs):
        '''
        set up how to return based on where you came from
        '''
        super().__init__(*args, **kwargs)
        self.fields['event_date'].initial = date.today()
        self.fields['pel_due_date'].initial = date.today()
        self.fields['bgs_due_date'].initial = date.today()

    class Meta:
        """Set up the attributes for the event form."""
        model = Event
        fields = '__all__'
        widgets = {
            'event_date': forms.DateInput(attrs={'class': 'datepicker'}),
            'pel_due_date': forms.DateInput(attrs={'class': 'datepicker'}),
            'bgs_due_date': forms.DateInput(attrs={'class': 'datepicker'})
        }

    class Media:
        """Add the media so that the datepicker will work."""
        css = {
            'all': ('css/lib/jquery-ui.css',)
        }
        js = ('js/lib/jquery-ui.min.js', )

talesofvalor/events/templates/events/event_character_print.html
{% extends "base.html" %}
{% load cms_tags %}


{% block bar_title %}Characters{% endblock bar_title %}
{% block title %}Characters{% endblock title %}

{% block content %}


<div class="row">
    <div id="character_list_filter" class="col-sm-7">
        <div class="box">
            
        </div>
    </div>
    <div id="character_list_actions" class="col-sm-5">
        <div class="box">
            
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        {% include "characters/includes/character_list.html" with objects=object_list id="character_list" caption="" %}
    </div>
</div>

{% include "includes/pagination.html" %}


{% endblock content %}

talesofvalor/events/templates/events/event_detail.html
{% extends "base.html" %}
{% load cms_tags sekizai_tags %}

{% block title %}{{ object.name }} | {{ object.event_date }}{% endblock title %}

{% block content %}



<h2><strong>Event Date:</strong>  {{ object.event_date|date:'m-d-Y'}}</h2>

{% if existing_registration %}
	<a href="{% url "registration:detail" pk=existing_registration.pk %}"><strong>You are registered for this event!</strong></a>
{% elif existing_registration_request %}
	<a href="{% url "registration:request_detail" pk=existing_registration_request.pk %}">You're <strong>requested a registration</strong> for this event.</a>
{% else %}
	<a href="{% url "events:register" pk=event.pk %}">Register for this event &hellip;</a>
{% endif %}

{% if object.summary %}
<h2>Summary</h2>
{{ object.summary }}
{% endif %}

{% if object.notes %}
<h2>Important Information</h2>
{{ object.notes }}
{% endif %}

{% if perms.players.view_any_player %}
<h2>Registered Players</h2>

<table class="list">
	<tr>
		<th>Name</th>
		<th>&nbsp;</th>
		<th>Date</th>
		<th colspan="3"></th>
	</tr>
{% for registration in object.registration_set.all %}
    <tr>
        <td><a href="{% url "registration:detail" pk=registration.pk %}">{{ registration }}</a></td>
        <td>{% if registration.registration_type == 'cast'%}CAST{% endif %}</td>
        <td>{{ event.event_date|date:'m-d-Y'}}</td>
        <td>{% comment %}<a class="btn btn-danger" href="{% url "registration:unregister" pk=registration.pk %}">remove&nbsp;registration</a>{% endcomment %}</td>
    </tr>
{% endfor %}
</table>

{% endif %}
{% endblock content %}

talesofvalor/events/templates/events/event_form.html
{% extends "base.html" %}
{% load cms_tags sekizai_tags %}

{% block title %}{{ object.name }} | {{ object.event_date }}{% endblock title %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>

{% addtoblock "js" %}
<script>
    $(document).ready(function() {
        $('.datepicker').datepicker();
    });
</script>
{% endaddtoblock %}
{% endblock content %}

talesofvalor/events/templates/events/event_list.html
{% extends "base.html" %}
{% load cms_tags sekizai_tags %}

{% block title %}Events{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-sm-4">
		<a href="{% url "events:event_past_list" %}">Past Events</a>
    </div>
    {% if perms.skills.add_skill %}
    <div class="col-sm-8">
        <div class="text-right">
		{% if perms.events.add_event and object_list %}<a href="{% url "events:event_create" %}">Add Event</a>{% endif %}
        </div>
    </div>
    {% endif %}
</div>
<table class="list">
	<tr>
		<th>Name</th>
		<th>Date</th>
		<th>Deadlines</th>
		<th>OOG</th>
		<th>BGA</th>
		<th colspan="3"></th>
	</tr>
{% for event in object_list %}
    <tr>
        <td><a href="{% url "events:event_detail" pk=event.pk %}">{{ event.name }}</a></td>
        <td>{{ event.event_date|date:'m-d-Y'}}</td>
        <td>BGA by {{ event.bgs_due_date|date:"m-d-Y"}}<br />PEL by {{ event.pel_due_date|date:'m-d-Y'}}</td>
        <td>{% if event.oog_p %}&#x2714;{% endif %}</td>
        <td>{% if event.bgs_p %}&#x2714;{% endif %}</td>
        <td>
            {% if event.registration %}
                <a class="text-success" href="{% url "registration:detail" pk=event.registration.pk %}">Registered!</a>
            {% elif event.registration_request %}
                <a href="{% url "registration:request_detail" pk=event.registration_request.pk %}">Requested Registration</a>
            {% else %}
                <a href="{% url "events:register" pk=event.pk %}">Register &hellip;</a>
            {% endif %}
        </td>
        <td>{% if perms.events.change_event %}<a href="{% url "events:event_update" pk=event.pk %}">edit</a>{% else %}&nbsp;{% endif %}</td>
    </tr>
{% empty %}

    <tr><td colspan="2">No Events Yet.{% if perms.events.add_event %}  <a href="{% url "events:event_create" %}">Add one&hellip;</a>{% endif %}</td></tr>
{% endfor %}
</table>

{% endblock content %}

talesofvalor/events/templates/events/event_past_list.html
{% extends "base.html" %}
{% load cms_tags sekizai_tags %}

{% block title %}Events{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-sm-4">
		<a href="{% url "events:event_list" %}">Current Events</a>
    </div>
    {% if perms.events.add_event %}
    <div class="col-sm-8">
        <div class="text-right">
		{% if perms.events.add_event and object_list %}<a href="{% url "events:event_create" %}">Add Event</a>{% endif %}
        </div>
    </div>
    {% endif %}
</div>
<table class="list">
	<tr>
		<th>Name</th>
		<th>Date</th>
		<th>Deadlines</th>
		<th>OOG</th>
		<th>BGA</th>
		<th colspan="2"></th>
	</tr>
{% for event in object_list %}
    <tr>
        <td><a href="{% url "events:event_detail" pk=event.pk %}">{{ event.name }}</a></td>
        <td>{{ event.event_date|date:'m-d-Y'}}</td>
        <td>BGS by {{ event.bgs_due_date|date:"m-d-Y"}}<br />PEL by {{ event.pel_due_date|date:'m-d-Y'}}</td>
        <td>{% if event.oog_p %}&#x2714;{% endif %}</td>
        <td>{% if event.bgs_p %}<a href="{% url "betweengameabilities:betweengameability_list" %}?event_id={{ event.id}}">BGA</a>{% endif %}</td>
        <td>{% if perms.events.change_event %}<a href="{% url "events:event_update" pk=event.pk %}">edit</a>{% else %}&nbsp;{% endif %}</td>
    </tr>
{% empty %}

    <tr><td colspan="2">No Events Yet.{% if perms.events.add_event %}  <a href="{% url "events:event_create" %}">Add one&hellip;</a>{% endif %}</td></tr>
{% endfor %}
</table>

{% endblock content %}

talesofvalor/events/templates/events/eventregistrationitem_detail.html
{% extends "base.html" %}
{% load cms_tags sekizai_tags %}

{% block title %}{{ object.name }}{% endblock title %}

{% block content %}

<h2>Events covered:</h2>
<ul>
	{% for event in object.events.all %}
		<li><a href="{% url "events:event_detail" pk=event.id %}">{{ event }}</a></li>
	{% endfor %}
</ul>

<p><strong>Cost:</strong>{{ object.price }}</p>
<p><strong>Still Available:</strong>{{ object.available|yesno }}</p>

{% endblock content %}

talesofvalor/events/templates/events/eventregistrationitem_form.html
{% extends "base.html" %}
{% load cms_tags sekizai_tags %}

{% block title %}{{ object.name }} | {{ object.event_date }}{% endblock title %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>

{% endblock content %}

talesofvalor/events/templates/events/eventregistrationitem_list.html
{% extends "base.html" %}
{% load cms_tags sekizai_tags %}

{% block title %}Event Registration Item{% endblock title %}

{% block content %}
<div class="row">
    <div id="eventregistrationitem_list_filter" class="col-sm-12">
        <div class="box">
        	<div class="event-year-list">
        		<ul class="flat-list">
        			<li><a href="{% url "events:eventregistrationitem_list" %}">All Years</a></li>
	        		{% for year in years %}
	        			<li><a href="{% url "events:eventregistrationitem_list" %}?year={{ year }}">{{ year }}</a></li>
	        		{% endfor %}
        		</ul>

        	</div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
		<table class="list">
			{% if perms.events.add_eventregistrationitem and object_list %}
			<tr>
				<td class="text-right" colspan="3"><a class="btn btn-primary" href="{% url "events:eventregistrationitem_create" %}">Add one&hellip;</a></td>
			</tr>
			{% endif %}
			<tr>
				<th>Name</th>
				<th>Events</th>
				<th></th>
			</tr>
		{% for item in object_list %}
		    <tr>
		        <td><a href="{% url "events:eventregistrationitem_update" pk=item.pk %}">{{ item.name }}</a></td>
		        <td>{% for event in item.events.all %}<a href="{% url "events:event_detail" pk=event.id %}">{{ event }}{% if not forloop.last%}</a>, {% endif %}{% endfor%}</td>
		        <td>{% if perms.events.change_eventregistrationitem %}<a href="{% url "events:eventregistrationitem_update" pk=item.pk %}">edit</a>{% else %}&nbsp;{% endif %}</td>
		    </tr>
		{% empty %}

		    <tr><td colspan="2">No Events Yet.{% if perms.events.add_eventregistrationitem %}  <a href="{% url "events:eventregistrationitem_create" %}">Add one&hellip;</a>{% endif %}</td></tr>
		{% endfor %}
		</table>
		{% include "includes/pagination.html" %}
    </div>
</div>

{% endblock content %}

talesofvalor/events/templates/events/registration_cast_form.html
{% extends "base.html" %}
{% load cms_tags sekizai_tags %}

{% block title %}Register As Cast{% endblock title %}

{% block content %}

<!-- writes out the form tag automatically -->
<form action="" method="post">{% csrf_token %}

<table id="event_registration_second_half" class="data event-registration">
<tr>
	<td colspan="2"><h2>Food Information</h2></td>
</tr>
<tr>
	<td> {{ form.food_allergies.label_tag }} </td>
	<td> {{ form.food_allergies }} </td>
</tr>
<tr>
	<td> {{ form.vegetarian_flag }} </td>
	<td> <label for="id_vegetarian_flag">Vegetarian Meal Requested</label></td>
</tr>
<tr>
	<td> {{ form.vegan_flag }} </td>
	<td> <label for="id_vegan_flag">Vegan Meal Requested</label></td>
</tr>
<tr>
	<td colspan="2"><h2>Vehicle Information</h2></td>
</tr>
<tr>
	<td> {{ form.no_car_flag }} </td>
	<td> <label for="id_no_car_flag">No car on site</label></td>
</tr>
{% if form.vehicle_make.errors %}
<tr><td colspan="2">{{ form.vehicle_make.errors }}</td></tr>
{% endif %}
<tr>
    <td>{{ form.vehicle_make.label_tag }}</td>
    <td>
		{{ form.vehicle_make }}{% if form.vehicle_make.help_text %}<br />{{ form.vehicle_make.help_text }}{% endif %}
	</td>
</tr>
{% if form.vehicle_model.errors %}
<tr><td colspan="2">{{ form.vehicle_model.errors }}</td></tr>
{% endif %}
<tr>
    <td>{{ form.vehicle_model.label_tag }}</td>
    <td>
		{{ form.vehicle_model }}{% if form.vehicle_model.help_text %}<br />{{ form.vehicle_model.help_text }}{% endif %}
	</td>
</tr>
{% if form.vehicle_color.errors %}
<tr><td colspan="2">{{ form.vehicle_color.errors }}</td></tr>
{% endif %}
<tr>
    <td>{{ form.vehicle_color.label_tag }}</td>
    <td>
		{{ form.vehicle_color }}{% if form.vehicle_color.help_text %}<br />{{ form.vehicle_color.help_text }}{% endif %}
	</td>
</tr>
{% if form.vehicle_registration.errors %}
<tr><td colspan="2">{{ form.vehicle_registration.errors }}</td></tr>
{% endif %}
<tr>
    <td>{{ form.vehicle_registration.label_tag }}</td>
    <td>
		{{ form.vehicle_registration }}{% if form.vehicle_registration.help_text %}<br />{{ form.vehicle_registration.help_text }}{% endif %}
	</td>
</tr>
{% if form.site_transportation.errors %}
<tr><td colspan="2">{{ form.site_transportation.errors }}</td></tr>
{% endif %}
<tr>
	<td>{{ form.site_transportation.label_tag }}
	</td>
    <td>
		{{ form.site_transportation }}{% if form.site_transportation.help_text %}<br />{{ form.site_transportation.help_text }}{% endif %}
	</td>
</tr>
<tr>
	<td colspan="2"><h2>Additional Information:</h2></td>
</tr>
{% if form.local_contact.errors %}
<tr><td colspan="2">{{ form.local_contact.errors }}</td></tr>
{% endif %}
<tr>
    <td>{{ form.local_contact.label_tag }}</td>
    <td>
		{{ form.local_contact }}{% if form.local_contact.help_text %}<br />{{ form.local_contact.help_text }}{% endif %}
	</td>
</tr>
{% if form.notes.errors %}
<tr><td colspan="2">{{ form.notes.errors }}</td></tr>
{% endif %}
<tr>
	<td>{{ form.notes.label_tag }}
	</td>
    <td>
		{{ form.notes }}{% if form.notes.help_text %}<br />{{ form.notes.help_text }}{% endif %}
	</td>
</tr>
</table>    
<input type="submit" value="Register" />
</form>
{% endblock content %}

talesofvalor/events/templates/events/registration_no_scheduled_event.html
{% extends "base.html" %}
{% load cms_tags sekizai_tags %}

{% block title %}No scheduled events at this time.{% endblock title %}

{% block content %}


Sorry, there are no currently scheduled events.

{% endblock content %}